### ISSUE TITLE
Typo causes fail in  Ipython-pandas-tips-and-tricks.ipynb

### ISSUE THREAD

**Issue by maverickactuary** [chris1610/pbpython#10]
\#SALES=pd.read_csv("../data/sample-sales-tax.csv", parse_dates='True') # AKH fails
SALES=pd.read_csv("../data/sample-sales-tax.csv", parse_dates=True) # AKH works

As a matter of style I would probably prefer the (excellent!) qgrid plugin to have been imported at the top. Caought it later though...

**Comment by chris1610** [comment]
Fixed. Thanks.
