### ISSUE TITLE
Typos in Forecasting-with-prophet.ipynb  causes missing file error

### ISSUE THREAD

**Issue by maverickactuary** [chris1610/pbpython#11]
data_file = "..\data\All Web Site Data Audience Overview.xlsx" should be 
data_file = "..\data\All-Web-Site-Data-Audience-Overview.xlsx"

Separately m2.plot_components(forecast2); is taking an *age* to finish, even with a laptop beast. 
I'm not sure it will.

**Comment by chris1610** [comment]
I think there are some issues with running prophet on windows machines and certain operations taking a long time. It seems to run relatively quickly on my stock linux laptop.
