### ISSUE TITLE
Needing to consider the case of an empty list

### ISSUE THREAD

**Issue by IcToxi** [chris1610/pbpython#17]
Hi Mr. Chris,

I recently learned the idea in your article _Updated: Using Pandas To Create an Excel Diff_ , and I noticed that there was a function report_diff that did not take into account the case of empty lists. If there is no change, an error occurs. I think you should write like this.

> def report_diff(x):
>>if any(x):
>>>return x[0] if x[0] == x[1] else '{} ---> {}'.format(*x)

Thanks!

**Comment by chris1610** [comment]
Yes. That's a good point. I'll update it shortly.

Thank you.

**Comment by chris1610** [comment]
Closing this out. The updated article I posted includes a fix for this bug. Thanks for pointing it out!
