### ISSUE TITLE
ValueError: Cannot describe a DataFrame without columns

### ISSUE THREAD

**Issue by scheung38** [chris1610/pbpython#2]
Code is located in code/script.py

and 

data in directory as per your example But upon running I get

```

from flask import Flask
import pandas as pd
import numpy as np
import glob

all_data = pd.DataFrame()

for f in glob.glob("../data/sales*.xlsx"):
    df = pd.read_excel(f)
    all_data = all_data.append(df, ignore_index=True)

all_data.describe()

```

    raise ValueError("Cannot describe a DataFrame without columns")
    ValueError: Cannot describe a DataFrame without columns

**Comment by chris1610** [comment]
If you try read just one file and looking at the data, does it work correctly? I suspect the process is not finding your files and you have an empty dataframe.

**Comment by ahlusar1989** [comment]
@chris1610 @scheung38 I tried to replicate this with one file and with more than one. I am not running into the error. @scheung38 Are you initializing a new dataframe object?
